name: Build Launcher

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Codigo
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Instalar Dependencias
      run: npm install

    - name: Criar pastas de saida
      shell: bash
      run: mkdir -p dist/Windows dist/Mac dist/Linux

    - name: Compilar Windows
      if: matrix.os == 'windows-latest'
      run: npm run build:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compilar Mac
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compilar Linux
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Enviar Arquivo Windows (Artefato)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-Windows
        path: dist/Windows/*.exe

    - name: Enviar Arquivo Mac (Artefato)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-Mac
        path: |
          dist/Mac/*.dmg
          dist/Mac/*.zip

    - name: Enviar Arquivo Linux (Artefato)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Launcher-Linux
        path: |
          dist/Linux/*.AppImage
          dist/Linux/*.tar.gz
